public class Sistema {
    
    //TITULO
    public static void exibirIntroducao() {
        System.out.println("                                                  !_        ");
        System.out.println("                                                  |*~=-.,   ");
        System.out.println("                                                  |_,-'`    ");
        System.out.println("                                                  |         ");
        System.out.println("                                                  |         ");
        System.out.println("                   !_                           /   \\       ");
        System.out.println("                   |*`~-.,                     /,    \\      ");
        System.out.println("                   |.-~^`                     /#\"     \\     ");
        System.out.println("                   |                        _/##_   _  \\_  ");
        System.out.println("              _   _|  _   _   _            [ ]_[ ]_[ ]_[ ]  ");
        System.out.println("             [ ]_[ ]_[ ]_[ ]_[ ]            |_=_-=_ - =_|   ");
        System.out.println("           !_ |_=_ =-_-_  = =_|           !_ |=_= -    |    ");
        System.out.println("           |*`--,_- _        |            |*`~-.,= []  |    ");
        System.out.println("           |.-'|=     []     |   !_       |_.-\"`_-     |    ");
        System.out.println("           |   |_=- -        |   |*`~-.,  |  |=_-      |    ");
        System.out.println("      _  /   \\_|_=- _   _   _|  _|  _   /   \\|=_-      |    ");
        System.out.println("     [ ]/,    \\[ ]_[ ]_[ ]_[ ]_[ ]_[ ]_/,    \\[ ]=-    |    ");
        System.out.println("      |/#\"     \\_=-___=__=__- =-_ -=_ /#\"     \\| _ []  |    ");
        System.out.println("     _/##_   _  \\_-_ =  _____       _/##_   _  \\_ -    |\\   ");
        System.out.println("    [ ]_[ ]_[ ]_[ ]=_0~{_ _ _}~0   [ ]_[ ]_[ ]_[ ]=-   | \\  ");
        System.out.println("    |_=__-_=-_  =_|-=_ |  ,  |     |_=-___-_ =-__|_    |  \\ ");
        System.out.println("     | _- =-     |-_   | ((* |      |= _=       | -    |___\\");
       // System.out.println("     |= -_=      |=  _ |  `  |      |_-=_       |=_    |/+\| ");
        System.out.println("     | =_  -     |_ = _ `-.-`       | =_ = =    |=_-   ||+|| ");
        System.out.println("     |-_=- _     |=_   =            |=_= -_     |  =   ||+|| ");
        System.out.println("     |=_- /+\\    | -=               |_=- /+\\    |=_    |^^^| ");
        System.out.println("     |=_ |+|+|   |= -  -_,--,_      |_= |+|+|   |  -_  |=  | ");
        System.out.println("     |  -|+|+|   |-_=  / |  | \\     |=_ |+|+|   |-=_   |_-/  ");
        System.out.println("     |=_=|+|+|   | =_= | |  | |     |_- |+|+|   |_ =   |=/   ");
        System.out.println("     | _ ^^^^^   |= -  | |    |=_=^^^^^   |_=-   |/       ");
        System.out.println("     |=_ =       | =_-_| |  | |     |   =_      | -_   |    ");
        System.out.println("     |_=-_       |=_=  | |  | |     |=_=        |=-    |    ");
        System.out.println("__________________________________________________________________");
        System.out.println("                     Bem-vindo ao jogo!                        ");
    
    
    }

    //MENU

    public static void menuJogo(){
        System.out.println("***----------------------------------------------------***");
        System.out.println("                    Iniciar o Jogo!                       ");
        System.out.println("***----------------------------------------------------***");
        System.out.println("                    Descrição do Jogo                     ");
        System.out.println("***----------------------------------------------------***");
        System.out.println("                    Crétidos do Jogo                      ");
        System.out.println("***----------------------------------------------------***");

    }

    //MAPA DO JOGO 
    public static void mapaGeral(){

      
    }

}
