

public class Sistema{

    String mensagem = """
            
            Confronto das Sombras: A Luta Pela Sobrevivência
   ——————————————————————————————————————————————————————————————————————————————— 
       Escolha seu herói e enfrente inimigos poderosos em batalhas intensas. 
       Explore um mundo sombrio, onde suas decisões e habilidades serão cruciais 
       para sobreviver e derrotar as forças das trevas. A sobrevivência é a chave 
   ———————————————————————————————————————————————————————————————————————————————
                    Você está pronto para o desafio?

 ░▄▀▀▀▀▄░░▄▄
█░░░░░░▀▀░░█░░░░░░▄░▄
█░║░░░░██░████████████ 
█░░░░░░▄▄░░█░░░░░░▀░▀
░▀▄▄▄▄▀░░▀▀
                   

            """;



        public String men (){
            return mensagem;
        }

}